ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += saul_adc
endif

ifneq (,$(filter ztimer,$(USEMODULE)))
  USEMODULE += ztimer_periph
  USEMODULE += ztimer_convert
  USEMODULE += ztimer_extend
endif
include $(RIOTCPU)/kinetis/Makefile.dep
